apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-backend
  template:
    metadata:
      labels:
        app: crypto-backend
    spec:
      containers:
        - name: backend
          image: fichofinki/crypto-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}
          envFrom:
            - secretRef:
                name: backend-db-secret
            - configMapRef:
                name: backend-config
